/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

type DecisionLogMetadata struct {
	BuildNumber int32 `json:"build_number,omitempty"`
	ProjectId string `json:"project_id,omitempty"`
	SshRerun bool `json:"ssh_rerun,omitempty"`
	Vcs *DecisionLogMetadataVcs `json:"vcs,omitempty"`
}
