/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Info about the latest workflow the job was a part of.
type JobDetailsLatestWorkflow struct {
	// The unique ID of the workflow.
	Id string `json:"id"`
	// The name of the workflow.
	Name string `json:"name"`
}
