/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// The information you can supply when rerunning a workflow.
type RerunWorkflowParameters struct {
	// Whether to enable SSH access for the triggering user on the newly-rerun job. Requires the jobs parameter to be used and so is mutually exclusive with the from_failed parameter.
	EnableSsh bool `json:"enable_ssh,omitempty"`
	// Whether to rerun the workflow from the failed job. Mutually exclusive with the jobs parameter.
	FromFailed bool `json:"from_failed,omitempty"`
	// A list of job IDs to rerun.
	Jobs []string `json:"jobs,omitempty"`
	// Completes rerun using sparse trees logic, an optimization for workflows that have disconnected subgraphs. Requires jobs parameter and so is mutually exclusive with the from_failed parameter.
	SparseTree bool `json:"sparse_tree,omitempty"`
}
