/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Trends aggregated across a workflow or branch for a project.
type InlineResponse2003Trends struct {
	// The trend value for total credits consumed.
	TotalCreditsUsed float32 `json:"total_credits_used"`
	// The 95th percentile duration among a group of workflow runs.
	P95DurationSecs float32 `json:"p95_duration_secs"`
	// The trend value for total number of runs.
	TotalRuns float32 `json:"total_runs"`
	// The trend value for the success rate.
	SuccessRate float32 `json:"success_rate"`
}
