/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Trends for a single project, across all branches.
type InlineResponse2005Trends struct {
	// The trend value for total credits consumed.
	TotalCreditsUsed float32 `json:"total_credits_used"`
	// Trend value for total duration.
	TotalDurationSecs float32 `json:"total_duration_secs"`
	// The trend value for total number of runs.
	TotalRuns float32 `json:"total_runs"`
	// The trend value for the success rate.
	SuccessRate float32 `json:"success_rate"`
}
