/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

type ContextIdRestrictionsBody struct {
	// Deprecated - Use \"restriction_type\" and \"restriction_value\" instead.  The project ID to use for a project restriction. This is mutually exclusive with restriction_type and restriction_value and implies restriction_type is \"project\". 
	ProjectId string `json:"project_id,omitempty"`
	RestrictionType string `json:"restriction_type,omitempty"`
	RestrictionValue string `json:"restriction_value,omitempty"`
}
