/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Metrics and trends data aggregated for a given project.
type InlineResponse2003ProjectData struct {
	Metrics *InlineResponse2003ProjectDataMetrics `json:"metrics"`
	Trends *InlineResponse2003ProjectDataTrends `json:"trends"`
}
