/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

import (
	"time"
)

type InlineResponse2008Items struct {
	// The name of the workflow.
	Name    string                     `json:"name"`
	Metrics *InlineResponse2008Metrics `json:"metrics"`
	// The timestamp of the first build within the requested reporting window.
	WindowStart time.Time `json:"window_start"`
	// The timestamp of the last build within the requested reporting window.
	WindowEnd time.Time `json:"window_end"`
	// The unique ID of the project
	ProjectId *any `json:"project_id"`
}
