/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

type PatchClaimsRequest struct {
	Audience []string `json:"audience,omitempty"`
	Ttl string `json:"ttl,omitempty"`
}
