/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

type ProjectSettingsAdvanced struct {
	// Except for the default branch, cancel running pipelines on a branch when a new pipeline starts on that branch.
	AutocancelBuilds bool `json:"autocancel_builds,omitempty"`
	// Run builds for pull requests from forks.
	BuildForkPrs bool `json:"build_fork_prs,omitempty"`
	// Once enabled, we will only build branches that have associated pull requests open.
	BuildPrsOnly bool `json:"build_prs_only,omitempty"`
	// When set to true, job re-runs with SSH debugging access will be disabled for the project.
	DisableSsh bool `json:"disable_ssh,omitempty"`
	// Run builds for forked pull requests with this project's configuration, environment variables, and secrets.
	ForksReceiveSecretEnvVars bool `json:"forks_receive_secret_env_vars,omitempty"`
	// Free and Open Source. Enabling this grants additional credits, and lets others see your builds, both through the web UI and the API.
	Oss bool `json:"oss,omitempty"`
	// Report the status of every pushed commit to GitHub's status API. Updates reported per job.
	SetGithubStatus bool `json:"set_github_status,omitempty"`
	// Enabling allows you to conditionally trigger configurations outside of the primary `.circleci` parent directory.
	SetupWorkflows bool `json:"setup_workflows,omitempty"`
	// Whether updating these settings requires a user to be an organization administrator. When disabled, updating settings can be done by any member.
	WriteSettingsRequiresAdmin bool `json:"write_settings_requires_admin,omitempty"`
	// This field is used in conjunction with the `build_prs_only`, it allows you to specify a list of branches that will always triger a build. The value passed will overwrite the existing value.
	PrOnlyBranchOverrides []string `json:"pr_only_branch_overrides,omitempty"`
}
