/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

type InlineResponse2007Flakytests struct {
	TimeWasted *AllOfinlineResponse2007FlakytestsTimeWasted `json:"time-wasted,omitempty"`
	// The date and time when workflow was created.
	WorkflowCreatedAt string `json:"workflow-created-at"`
	// The ID of the workflow associated with the provided test counts
	WorkflowId *any `json:"workflow-id"`
	// The class the test belongs to.
	Classname string `json:"classname"`
	// The number of the pipeline.
	PipelineNumber *AllOfinlineResponse2007FlakytestsPipelineNumber `json:"pipeline-number"`
	// The name of the workflow.
	WorkflowName string `json:"workflow-name"`
	// The name of the test.
	TestName string `json:"test-name"`
	// The name of the job.
	JobName string `json:"job-name"`
	// The number of the job.
	JobNumber *AllOfinlineResponse2007FlakytestsJobNumber `json:"job-number"`
	// The number of times the test flaked.
	TimesFlaked int64 `json:"times-flaked"`
	// The source of the test.
	Source string `json:"source"`
	// The file the test belongs to.
	File string `json:"file"`
}
