/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Metrics aggregated across a workflow or branchfor a project.
type InlineResponse2003Metrics struct {
	// The total credits consumed over the current timeseries interval.
	TotalCreditsUsed int64 `json:"total_credits_used"`
	// The 95th percentile duration among a group of workflow runs.
	P95DurationSecs float32 `json:"p95_duration_secs"`
	// The total number of runs, including runs that are still on-hold or running.
	TotalRuns int64 `json:"total_runs"`
	SuccessRate float32 `json:"success_rate"`
}
