/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

type Collaboration struct {
	// The UUID of the organization
	Id string `json:"id"`
	// The VCS provider
	VcsType string `json:"vcs-type"`
	// The name of the organization
	Name string `json:"name"`
	// URL to the user's avatar on the VCS
	AvatarUrl string `json:"avatar_url"`
	// The slug of the organization
	Slug string `json:"slug"`
}
