/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci
import (
	"time"
)

type OrgIdUsageExportJobBody struct {
	// The start date & time (inclusive) of the range from which data will be pulled. Must be no more than one year ago.
	Start time.Time `json:"start"`
	// The end date & time (inclusive) of the range from which data will be pulled. Must be no more than 31 days after `start`.
	End time.Time `json:"end"`
	SharedOrgIds []string `json:"shared_org_ids,omitempty"`
}
