/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Metric trends aggregated across all workflows and branches for a project.
type InlineResponse2003ProjectDataTrends struct {
	// The trend value for total number of runs.
	TotalRuns float32 `json:"total_runs"`
	// Trend value for total duration.
	TotalDurationSecs float32 `json:"total_duration_secs"`
	// The trend value for total credits consumed.
	TotalCreditsUsed float32 `json:"total_credits_used"`
	// The trend value for the success rate.
	SuccessRate float32 `json:"success_rate"`
	// Trend value for the average number of runs per day.
	Throughput float32 `json:"throughput"`
}
