/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Project level timeseries metrics response
type InlineResponse2004 struct {
	// A token to pass as a `page-token` query parameter to return the next page of results.
	NextPageToken string `json:"next_page_token"`
	// Aggregate metrics for a workflow at a time granularity
	Items []InlineResponse2004Items `json:"items"`
}
