/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Info about a status of the parallel run.
type JobDetailsParallelRuns struct {
	// Index of the parallel run.
	Index int64 `json:"index"`
	// Status of the parallel run.
	Status string `json:"status"`
}
