/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Metrics relating to a workflow job's runs.
type InlineResponse20010Metrics struct {
	// The total number of runs, including runs that are still on-hold or running.
	TotalRuns int64 `json:"total_runs"`
	// The number of failed runs.
	FailedRuns int64 `json:"failed_runs"`
	// The number of successful runs.
	SuccessfulRuns int64 `json:"successful_runs"`
	DurationMetrics *InlineResponse20010MetricsDurationMetrics `json:"duration_metrics"`
	SuccessRate float32 `json:"success_rate"`
	// The total credits consumed by the job in the aggregation window. Note that Insights is not a real time financial reporting tool and should not be used for credit reporting.
	TotalCreditsUsed int64 `json:"total_credits_used"`
	// The average number of runs per day.
	Throughput float32 `json:"throughput"`
}
