/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Metrics relating to a workflow's runs.
type InlineResponse2008Metrics struct {
	// The total number of runs, including runs that are still on-hold or running.
	TotalRuns int64 `json:"total_runs"`
	// The number of successful runs.
	SuccessfulRuns int64 `json:"successful_runs"`
	// The mean time to recovery (mean time between failures and their next success) in seconds.
	Mttr int64 `json:"mttr"`
	// The total credits consumed by the workflow in the aggregation window. Note that Insights is not a real time financial reporting tool and should not be used for credit reporting.
	TotalCreditsUsed int64 `json:"total_credits_used"`
	// The number of failed runs.
	FailedRuns int64 `json:"failed_runs"`
	SuccessRate float32 `json:"success_rate"`
	DurationMetrics *InlineResponse2008MetricsDurationMetrics `json:"duration_metrics"`
	// The number of recovered workflow executions per day.
	TotalRecoveries int64 `json:"total_recoveries"`
	// The average number of runs per day.
	Throughput float32 `json:"throughput"`
}
