/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci
import (
	"time"
)

type InlineResponse2001Items struct {
	// The name of the environment variable
	Variable string `json:"variable"`
	// The date and time the environment variable was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time the environment variable was updated
	UpdatedAt time.Time `json:"updated_at"`
	// ID of the context (UUID)
	ContextId string `json:"context_id"`
}
