/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Info about a pipeline the job is a part of.
type JobDetailsPipeline struct {
	// The unique ID of the pipeline.
	Id string `json:"id"`
}
