/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

type PipelineContinueBody struct {
	// A pipeline continuation key.
	ContinuationKey string `json:"continuation-key"`
	// A configuration string for the pipeline.
	Configuration string `json:"configuration"`
	// An object containing pipeline parameters and their values. Pipeline parameters have the following size limits: 100 max entries, 128 maximum key length, 512 maximum value length.
	Parameters map[string]any `json:"parameters,omitempty"`
}
