/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci
import (
	"time"
)

// A summary of the trigger.
type PipelineListResponseTrigger struct {
	// The type of trigger.
	Type_ string `json:"type"`
	// The date and time the trigger was received.
	ReceivedAt time.Time `json:"received_at"`
	Actor *PipelineListResponseTriggerActor `json:"actor"`
}
