/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

type InlineResponse2003 struct {
	// The unique ID of the organization
	OrgId *Object `json:"org_id,omitempty"`
	// The unique ID of the project
	ProjectId *Object `json:"project_id,omitempty"`
	ProjectData *InlineResponse2003ProjectData `json:"project_data,omitempty"`
	// A list of metrics and trends data for workflows for a given project.
	ProjectWorkflowData []InlineResponse2003ProjectWorkflowData `json:"project_workflow_data,omitempty"`
	// A list of metrics and trends data for branches for a given project.
	ProjectWorkflowBranchData []InlineResponse2003ProjectWorkflowBranchData `json:"project_workflow_branch_data,omitempty"`
	// A list of all the branches for a given project.
	AllBranches []string `json:"all_branches,omitempty"`
	// A list of all the workflows for a given project.
	AllWorkflows []string `json:"all_workflows,omitempty"`
}
