/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci
import (
	"time"
)

type ClaimResponse struct {
	Audience []string `json:"audience,omitempty"`
	AudienceUpdatedAt time.Time `json:"audience_updated_at,omitempty"`
	OrgId string `json:"org_id"`
	ProjectId string `json:"project_id,omitempty"`
	Ttl string `json:"ttl,omitempty"`
	TtlUpdatedAt time.Time `json:"ttl_updated_at,omitempty"`
}
