/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci
import (
	"time"
)

type Webhook struct {
	// URL to deliver the webhook to. Note: protocol must be included as well (only https is supported)
	Url string `json:"url"`
	// Whether to enforce TLS certificate verification when delivering the webhook
	VerifyTls bool `json:"verify-tls"`
	// The unique ID of the webhook
	Id string `json:"id"`
	// Masked value of the secret used to build an HMAC hash of the payload and passed as a header in the webhook request
	SigningSecret string `json:"signing-secret"`
	// The date and time the webhook was last updated.
	UpdatedAt time.Time `json:"updated-at"`
	// Name of the webhook
	Name string `json:"name"`
	// The date and time the webhook was created.
	CreatedAt time.Time `json:"created-at"`
	Scope *InlineResponse20014Scope `json:"scope"`
	// Events that will trigger the webhook
	Events []string `json:"events"`
}
