/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Project branches response.
type InlineResponse2006 struct {
	// The unique ID of the organization
	OrgId *Object `json:"org_id"`
	// The unique ID of the project
	ProjectId *Object `json:"project_id"`
	// A list of all the branches for a given project.
	Branches []string `json:"branches"`
}
