/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Workflow level aggregated metrics and trends response
type InlineResponse20011 struct {
	Metrics *InlineResponse20011Metrics `json:"metrics"`
	Trends *InlineResponse20011Trends `json:"trends"`
	// A list of all the workflow names for a given project.
	WorkflowNames []string `json:"workflow_names"`
}
