/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Metrics relating to the duration of runs for a workflow.
type InlineResponse2004MetricsDurationMetrics struct {
	// The minimum duration, in seconds, among a group of runs.
	Min int64 `json:"min"`
	// The median duration, in seconds, among a group of runs.
	Median int64 `json:"median"`
	// The max duration, in seconds, among a group of runs.
	Max int64 `json:"max"`
	// The 95th percentile duration, in seconds, among a group of runs.
	P95 int64 `json:"p95"`
	// The total duration, in seconds, added across a group of runs.
	Total int64 `json:"total"`
}
