/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

type DecisionLogMetadataVcs struct {
	Branch string `json:"branch,omitempty"`
	OriginRepositoryUrl string `json:"origin_repository_url,omitempty"`
	ReleaseTag string `json:"release_tag,omitempty"`
	TargetRepositoryUrl string `json:"target_repository_url,omitempty"`
}
