/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// The parameters for a create schedule request
type CreateScheduleParameters struct {
	// Name of the schedule.
	Name string `json:"name"`
	// Timetable that specifies when a schedule triggers.
	Timetable *AnyOfCreateScheduleParametersTimetable `json:"timetable"`
	// The attribution-actor of the scheduled pipeline.
	AttributionActor string `json:"attribution-actor"`
	// Pipeline parameters represented as key-value pairs. Must contain branch or tag.
	Parameters map[string]any `json:"parameters"`
	// Description of the schedule.
	Description string `json:"description,omitempty"`
}
