/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// An environment variable is a map containing a value and an optional timestamp.
type EnvironmentVariable1 struct {
	// The name of the environment variable.
	Name string `json:"name"`
	// The value of the environment variable.
	Value string `json:"value"`
	// The creation timestamp of the environment variable.
	CreatedAt *Object `json:"created-at,omitempty"`
}
