/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci
import (
	"time"
)

type UsageExportJob struct {
	UsageExportJobId string `json:"usage_export_job_id"`
	State string `json:"state"`
	Start time.Time `json:"start"`
	End time.Time `json:"end"`
	// A list of pre signed urls that the client can use to download the results of a Usage Export.
	DownloadUrls []interface{} `json:"download_urls"`
}
