/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Test counts for a given pipeline number
type InlineResponse20012TestCounts struct {
	// The number of tests with the error status
	Error_ int64 `json:"error"`
	// The number of tests with the failure status
	Failure int64 `json:"failure"`
	// The number of tests with the skipped status
	Skipped int64 `json:"skipped"`
	// The number of tests with the success status
	Success int64 `json:"success"`
	// The total number of tests
	Total int64 `json:"total"`
}
