/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// The parameters for a create webhook request
type WebhookBody struct {
	// Name of the webhook
	Name string `json:"name"`
	// Events that will trigger the webhook
	Events []string `json:"events"`
	// URL to deliver the webhook to. Note: protocol must be included as well (only https is supported)
	Url string `json:"url"`
	// Whether to enforce TLS certificate verification when delivering the webhook
	VerifyTls bool `json:"verify-tls"`
	// Secret used to build an HMAC hash of the payload and passed as a header in the webhook request
	SigningSecret string `json:"signing-secret"`
	Scope *WebhookScope `json:"scope"`
}
