/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// The scope in which the relevant events that will trigger webhooks
type InlineResponse20014Scope struct {
	// ID of the scope being used (at the moment, only project ID is supported)
	Id string `json:"id"`
	// Type of the scope being used
	Type_ string `json:"type"`
}
