/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Information about the VCS that hosts the project source code.
type ProjectVcsInfo struct {
	// URL to the repository hosting the project's code
	VcsUrl string `json:"vcs_url"`
	// The VCS provider
	Provider string `json:"provider"`
	DefaultBranch string `json:"default_branch"`
}
