/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type InlineResponse2009Items struct {
	// The unique ID of the workflow.
	Id string `json:"id"`
	// The VCS branch of a Workflow's trigger.
	Branch string `json:"branch"`
	// The duration in seconds of a run.
	Duration int64 `json:"duration"`
	// The date and time the workflow was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time the workflow stopped.
	StoppedAt time.Time `json:"stopped_at"`
	// The number of credits used during execution. Note that Insights is not a real time financial reporting tool and should not be used for credit reporting.
	CreditsUsed int64 `json:"credits_used"`
	// Workflow status.
	Status string `json:"status"`
	// Describes if the job is an approval job or not. Approval jobs are intermediary jobs that are created to pause the workflow until approved.
	IsApproval bool `json:"is_approval"`
}
