/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ContextProjectRestrictionsList struct {
	Items []ContextProjectRestrictionsListItems `json:"items,omitempty"`
	// Token that can be used to retrieve next page of results
	NextPageToken string `json:"next_page_token,omitempty"`
}
