/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse20012MostFailedTests struct {
	// The 95th percentile duration, in seconds, among a group of test runs.
	P95Duration float64 `json:"p95_duration"`
	// The total number of times the test was run.
	TotalRuns int64 `json:"total_runs"`
	// The class the test belongs to.
	Classname string `json:"classname"`
	// The number of times the test failed
	FailedRuns int64 `json:"failed_runs"`
	// Whether the test is flaky.
	Flaky bool `json:"flaky"`
	// The source of the test.
	Source string `json:"source"`
	// The file the test belongs to.
	File string `json:"file"`
	// The name of the job.
	JobName string `json:"job_name"`
	// The name of the test.
	TestName string `json:"test_name"`
}
