/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Metrics for a single org metrics.
type InlineResponse2005OrgDataMetrics struct {
	// The total number of runs, including runs that are still on-hold or running.
	TotalRuns int64 `json:"total_runs"`
	// Total duration, in seconds.
	TotalDurationSecs int64 `json:"total_duration_secs"`
	// The total credits consumed over the current timeseries interval.
	TotalCreditsUsed int64 `json:"total_credits_used"`
	SuccessRate float32 `json:"success_rate"`
	// The average number of runs per day.
	Throughput float32 `json:"throughput"`
}
