/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ContextProjectRestrictionsListItems struct {
	// UUID of the context
	ContextId string `json:"context_id,omitempty"`
	// UUID of the restriction
	Id string `json:"id,omitempty"`
	// Deprecated - For \"project\" restrictions read the project ID from \"restriction_value\" instead.  UUID of the project used in a project restriction. 
	ProjectId string `json:"project_id,omitempty"`
	// Contains a human-readable reference for the restriction. For \"project\" restrictions this is the name of the project.  May be null. 
	Name string `json:"name,omitempty"`
	// Type of the restriction
	RestrictionType string `json:"restriction_type,omitempty"`
	// Value used to evaluate the restriction
	RestrictionValue string `json:"restriction_value,omitempty"`
}
