/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type DecisionLog struct {
	CreatedAt time.Time `json:"created_at,omitempty"`
	Decision *Decision `json:"decision,omitempty"`
	Id string `json:"id,omitempty"`
	Metadata *DecisionLogMetadata `json:"metadata,omitempty"`
	// policy-name-to-hash-map
	Policies map[string]string `json:"policies,omitempty"`
	TimeTakenMs int32 `json:"time_taken_ms,omitempty"`
}
