/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The parameters for an update schedule request
type UpdateScheduleParameters struct {
	// Description of the schedule.
	Description string `json:"description,omitempty"`
	// Name of the schedule.
	Name string `json:"name,omitempty"`
	Timetable *SchedulescheduleidTimetable `json:"timetable,omitempty"`
	// The attribution-actor of the scheduled pipeline.
	AttributionActor string `json:"attribution-actor,omitempty"`
	// Pipeline parameters represented as key-value pairs. Must contain branch or tag.
	Parameters map[string]Object `json:"parameters,omitempty"`
}
