/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Context struct {
	// The unique ID of the context.
	Id string `json:"id"`
	// The user defined name of the context.
	Name string `json:"name"`
	// The date and time the context was created.
	CreatedAt time.Time `json:"created_at"`
}
