/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BundleDiff struct {
	Created []string `json:"created,omitempty"`
	Deleted []string `json:"deleted,omitempty"`
	Modified []string `json:"modified,omitempty"`
}
