/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ContextBody struct {
	// The user defined name of the context.
	Name string `json:"name"`
	Owner *OneOfcontextBodyOwner `json:"owner"`
}
