/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetUsageExportJobStatus struct {
	UsageExportJobId string `json:"usage_export_job_id"`
	State string `json:"state"`
	// A list of pre signed urls that the client can use to download the results of a Usage Export.
	DownloadUrls []interface{} `json:"download_urls"`
	ErrorReason string `json:"error_reason,omitempty"`
}
