/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Information about executor used for a job.
type JobDetailsExecutor struct {
	// Resource class name.
	ResourceClass string `json:"resource_class"`
	// Executor type.
	Type_ string `json:"type,omitempty"`
}
