/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Metrics relating to a workflow's runs.
type InlineResponse2004Metrics struct {
	// The total number of runs, including runs that are still on-hold or running.
	TotalRuns int64 `json:"total_runs"`
	// The number of failed runs.
	FailedRuns int64 `json:"failed_runs"`
	// The number of successful runs.
	SuccessfulRuns int64 `json:"successful_runs"`
	// The average number of runs per day.
	Throughput float32 `json:"throughput"`
	// The median credits consumed over the current timeseries interval.
	MedianCreditsUsed int64 `json:"median_credits_used"`
	// The total credits consumed over the current timeseries interval.
	TotalCreditsUsed int64 `json:"total_credits_used"`
	DurationMetrics *InlineResponse2004MetricsDurationMetrics `json:"duration_metrics"`
}
