/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// A schedule response
type Schedule struct {
	// The unique ID of the schedule.
	Id string `json:"id"`
	// Timetable that specifies when a schedule triggers.
	Timetable *AnyOfScheduleTimetable `json:"timetable"`
	// The date and time the pipeline was last updated.
	UpdatedAt time.Time `json:"updated-at"`
	// Name of the schedule.
	Name string `json:"name"`
	// The date and time the pipeline was created.
	CreatedAt time.Time `json:"created-at"`
	// The project-slug for the schedule
	ProjectSlug string `json:"project-slug"`
	// Pipeline parameters represented as key-value pairs. Must contain branch or tag.
	Parameters map[string]Object `json:"parameters"`
	Actor *User1 `json:"actor"`
	// Description of the schedule.
	Description string `json:"description"`
}
