/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type InlineResponse2004Items struct {
	// The name of the workflow.
	Name string `json:"name"`
	// The start time for the earliest execution included in the metrics.
	MinStartedAt time.Time `json:"min_started_at"`
	// The end time of the last execution included in the metrics.
	MaxEndedAt time.Time `json:"max_ended_at"`
	// The start of the interval for timeseries metrics.
	Timestamp time.Time `json:"timestamp"`
	Metrics *InlineResponse2004Metrics `json:"metrics"`
}
