/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2003ProjectWorkflowData struct {
	// The name of the workflow.
	WorkflowName string `json:"workflow_name"`
	Metrics *InlineResponse2003Metrics `json:"metrics"`
	Trends *InlineResponse2003Trends `json:"trends"`
}
