/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The latest commit in the pipeline.
type PipelineListResponseVcsCommit struct {
	// The subject of the commit message.
	Subject string `json:"subject"`
	// The body of the commit message.
	Body string `json:"body"`
}
