/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Message from CircleCI execution platform.
type JobDetailsMessages struct {
	// Message type.
	Type_ string `json:"type"`
	// Information describing message.
	Message string `json:"message"`
	// Value describing the reason for message to be added to the job.
	Reason string `json:"reason,omitempty"`
}
