/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Summary metrics with trends for the entire org, and for each project.
type InlineResponse2005 struct {
	OrgData *InlineResponse2005OrgData `json:"org_data"`
	// Metrics for a single project, across all branches
	OrgProjectData []InlineResponse2005OrgProjectData `json:"org_project_data"`
	// A list of all the project names in the organization.
	AllProjects []string `json:"all_projects"`
}
