/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Decision struct {
	EnabledRules []string `json:"enabled_rules,omitempty"`
	HardFailures []Violation `json:"hard_failures,omitempty"`
	Reason string `json:"reason,omitempty"`
	SoftFailures []Violation `json:"soft_failures,omitempty"`
	Status string `json:"status"`
}
