/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// An error with a type and message.
type PipelineListResponseErrors struct {
	// The type of error.
	Type_ string `json:"type"`
	// A human-readable error message.
	Message string `json:"message"`
}
