/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Timetable that specifies when a schedule triggers.
type SchedulescheduleidTimetable struct {
	// Number of times a schedule triggers per hour, value must be between 1 and 60
	PerHour int32 `json:"per-hour,omitempty"`
	// Hours in a day in which the schedule triggers.
	HoursOfDay []int32 `json:"hours-of-day,omitempty"`
	// Days in a week in which the schedule triggers.
	DaysOfWeek []string `json:"days-of-week,omitempty"`
	// Days in a month in which the schedule triggers. This is mutually exclusive with days in a week.
	DaysOfMonth []int32 `json:"days-of-month,omitempty"`
	// Months in which the schedule triggers.
	Months []string `json:"months,omitempty"`
}
