/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The parameters for an update webhook request
type WebhookWebhookidBody struct {
	// Name of the webhook
	Name string `json:"name,omitempty"`
	// Events that will trigger the webhook
	Events []string `json:"events,omitempty"`
	// URL to deliver the webhook to. Note: protocol must be included as well (only https is supported)
	Url string `json:"url,omitempty"`
	// Secret used to build an HMAC hash of the payload and passed as a header in the webhook request
	SigningSecret string `json:"signing-secret,omitempty"`
	// Whether to enforce TLS certificate verification when delivering the webhook
	VerifyTls bool `json:"verify-tls,omitempty"`
}
