/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Trends for aggregated metrics across a workflow for a given time window.
type InlineResponse20011Trends struct {
	// The trend value for total number of runs.
	TotalRuns float32 `json:"total_runs"`
	// The trend value for number of failed runs.
	FailedRuns float32 `json:"failed_runs"`
	// The trend value for the success rate.
	SuccessRate float32 `json:"success_rate"`
	// Trend value for the 95th percentile duration for a workflow for a given time window.
	P95DurationSecs float32 `json:"p95_duration_secs"`
	// Trend value for the 50th percentile duration for a workflow for a given time window.
	MedianDurationSecs float32 `json:"median_duration_secs"`
	// The trend value for total credits consumed.
	TotalCreditsUsed float32 `json:"total_credits_used"`
	// trend for mean time to recovery (mean time between failures and their next success).
	Mttr float32 `json:"mttr"`
	// Trend value for the average number of runs per day.
	Throughput float32 `json:"throughput"`
}
