/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Project level test metrics response
type InlineResponse20012 struct {
	// The average number of tests executed per run
	AverageTestCount int64 `json:"average_test_count"`
	// Metrics for the most frequently failing tests
	MostFailedTests []InlineResponse20012MostFailedTests `json:"most_failed_tests"`
	// The number of tests with the same success rate being omitted from most_failed_tests
	MostFailedTestsExtra int64 `json:"most_failed_tests_extra"`
	// Metrics for the slowest running tests
	SlowestTests []InlineResponse20012MostFailedTests `json:"slowest_tests"`
	// The number of tests with the same duration rate being omitted from slowest_tests
	SlowestTestsExtra int64 `json:"slowest_tests_extra"`
	// The total number of test runs
	TotalTestRuns int64 `json:"total_test_runs"`
	// Test counts grouped by pipeline number and workflow id
	TestRuns []InlineResponse20012TestRuns `json:"test_runs"`
}
