/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2005OrgProjectData struct {
	// The name of the project.
	ProjectName string `json:"project_name"`
	Metrics *InlineResponse2005Metrics `json:"metrics"`
	Trends *InlineResponse2005Trends `json:"trends"`
}
