/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Flaky tests response
type InlineResponse2007 struct {
	// A list of all instances of flakes. Note that a test is no longer considered flaky after 2 weeks have passed without a flake. Each flake resets this timer.
	FlakyTests []InlineResponse2007Flakytests `json:"flaky-tests"`
	// A count of unique tests that have failed. If your project has N tests that have flaked multiple times each, this will be equal to N.
	TotalFlakyTests float64 `json:"total-flaky-tests"`
}
