/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Metrics aggregated across a workflow for a given time window.
type InlineResponse20011Metrics struct {
	// The total number of runs, including runs that are still on-hold or running.
	TotalRuns int64 `json:"total_runs"`
	// The number of successful runs.
	SuccessfulRuns int64 `json:"successful_runs"`
	// The mean time to recovery (mean time between failures and their next success) in seconds.
	Mttr int64 `json:"mttr"`
	// The total credits consumed by the workflow in the aggregation window. Note that Insights is not a real time financial reporting tool and should not be used for credit reporting.
	TotalCreditsUsed int64 `json:"total_credits_used"`
	// The number of failed runs.
	FailedRuns int64 `json:"failed_runs"`
	SuccessRate float32 `json:"success_rate"`
	// The number of runs that ran to completion within the aggregation window
	CompletedRuns int64 `json:"completed_runs"`
	// The timestamp of the first build within the requested reporting window.
	WindowStart time.Time `json:"window_start"`
	DurationMetrics *InlineResponse2008MetricsDurationMetrics `json:"duration_metrics"`
	// The timestamp of the last build within the requested reporting window.
	WindowEnd time.Time `json:"window_end"`
	// The average number of runs per day.
	Throughput float32 `json:"throughput"`
}
