/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Information about a project.
type JobDetailsProject struct {
	Id string `json:"id"`
	// Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped. For projects that use GitLab or GitHub App, use `circleci` as the `vcs-slug`, replace `org-name` with the organization ID (found in Organization Settings), and replace `repo-name` with the project ID (found in Project Settings).
	Slug string `json:"slug"`
	// The name of the project
	Name string `json:"name"`
	// URL to the repository hosting the project's code
	ExternalUrl string `json:"external_url"`
}
