/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A response to rerunning a workflow
type InlineResponse202 struct {
	// The ID of the newly-created workflow.
	WorkflowId string `json:"workflow_id"`
}
