/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2.
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Aggregated metrics for an org, with trends.
type InlineResponse2005OrgData struct {
	Metrics *InlineResponse2005OrgDataMetrics `json:"metrics"`
	Trends *InlineResponse2005OrgDataTrends `json:"trends"`
}
