version: 2.1

orbs:
  go: circleci/go@3.0.2

commands:
  store_results:
    steps:
      - store_artifacts:
          path: test-reports
      - store_test_results:
          path: test-reports

  setup:
    steps:
      - checkout
      - run: task mod-download

jobs:
  lint:
    executor:
      name: go/default
      tag: '1.24'
    steps:
      - setup
      - go/with-cache:
          golangci-lint: true
          steps:
            - run: task ci:diff
            - run: task ci:lint
      - store_results

  test:
    executor:
      name: go/default
      tag: '1.24'
    steps:
      - setup
      - go/with-cache:
          steps:
            - run: CIRCLE_TOKEN="${CCIPERSONALACCESSTOKEN_ASKSEC_310:-}" task ci:test
      - store_results


workflows:
  main:
    jobs:
      - lint
      - test:
          context: CircleCITestOrg-ccipat
      - test:
          name: test_no_secrets
